# https://pre-commit.com/hooks.html
# https://www.blopig.com/blog/2020/10/improving-your-python-code-quality-using-git-pre-commit-hook
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        # additional_dependencies: [flake8-bugbear]
        exclude: ^logs/
